### ISSUE TITLE
BLE-OTA-v1.4

### ISSUE THREAD

**Issue by vanbwodonk** [fbiego/ESP32_BLE_OTA_Android#3]
Hi,

Is this android already support your new BLE arduino with fatfs? 
Newest apk binary build is `BLE-OTA-v1.4.apk`

**Comment by Fabchick** [comment]
As far as I know this repo has only v1.0.
Sadly, the v1.4 is not here in git. The source code of this version would be very interesting for me because I want to implement this OTA behaviour on a different app connecting with a different microcontroller. @fbiego is it possible for you to update the source code in this repo? That would make me very happy.

**Comment by Fabchick** [comment]
fbiego, you are the best! :)

**Comment by vanbwodonk** [comment]
Thank you fbiego, closed now.
